/**
 * Vibe-Presets (§15).
 *
 * Presets sind AUSGANGSPUNKTE, keine fertigen Bearbeitungen. Sie enthalten nur
 * die Parameter, die den jeweiligen Look definieren — alles andere bleibt auf
 * dem Default. Wird ein Preset über "KI anpassen" angewendet, bekommt das
 * Modell diese Werte zusammen mit der Bildanalyse und verschiebt sie so, dass
 * sie zum konkreten Foto passen (z. B. weniger Lichter-Rücknahme, wenn der
 * Himmel ohnehin nicht überstrahlt ist).
 *
 * `vibe` ist die Textbeschreibung, die dabei an die KI übergeben wird.
 */

import type { CurvePoint, ParamValues } from './params.ts';

export interface Preset {
  id: string;
  name: string;
  category: string;
  description: string;
  /** Kurzbeschreibung des Looks für die KI-Anpassung. */
  vibe: string;
  values: Partial<ParamValues>;
  curve?: CurvePoint[];
}

const PRESET_CATEGORIES = [
  'Cinematic',
  'Automotive',
  'Natur',
  'Urban',
  'Film',
  'Schwarzweiß',
] as const;

export const PRESETS: Preset[] = [
  // ── Cinematic ────────────────────────────────────────────────────────────
  {
    id: 'cinematic-dark',
    name: 'Cinematic Dark',
    category: 'Cinematic',
    description: 'Zurückgenommene Lichter, tiefe Schatten, kühle Schattentönung.',
    vibe: 'cinematic, dunkel, leicht entsättigt, kühle Schatten mit warmen Lichtern, ruhige Filmästhetik',
    values: {
      exposure: -0.1,
      contrast: 14,
      highlights: -35,
      shadows: 14,
      whites: -10,
      blacks: -18,
      temperature: -8,
      tint: 3,
      vibrance: 10,
      saturation: -8,
      clarity: 8,
      texture: 3,
      dehaze: 4,
      hslOrangeSat: 8,
      hslBlueSat: 6,
      hslAquaSat: 5,
      hslBlueLum: -10,
      gradeShadowHue: 210,
      gradeShadowSat: 18,
      gradeHighHue: 40,
      gradeHighSat: 10,
      gradeBlending: 55,
      gradeBalance: -10,
      vignetteAmount: -18,
      vignetteMidpoint: 45,
      vignetteFeather: 60,
    },
  },
  {
    id: 'cinematic-cold',
    name: 'Cold Cinematic',
    category: 'Cinematic',
    description: 'Blaustichige Nacht- und Regenstimmung mit klarer Zeichnung.',
    vibe: 'kalt, blau, cinematic, technisch und nüchtern, Schatten deutlich blau getönt',
    values: {
      exposure: -0.12,
      contrast: 16,
      highlights: -30,
      shadows: 16,
      whites: -8,
      blacks: -20,
      temperature: -22,
      tint: 2,
      vibrance: 12,
      saturation: -10,
      clarity: 10,
      dehaze: 6,
      hslBlueSat: 14,
      hslAquaSat: 10,
      hslOrangeSat: 4,
      gradeShadowHue: 215,
      gradeShadowSat: 26,
      gradeMidHue: 205,
      gradeMidSat: 8,
      gradeHighHue: 200,
      gradeHighSat: 8,
      gradeBlending: 50,
      vignetteAmount: -20,
      vignetteFeather: 60,
    },
  },
  {
    id: 'cinematic-warm',
    name: 'Warm Cinematic',
    category: 'Cinematic',
    description: 'Warmer Filmlook mit weichen Lichtern und sattem Schwarz.',
    vibe: 'warm, cinematic, goldene Lichter, weiche Kontraste, nostalgisch aber sauber',
    values: {
      contrast: 12,
      highlights: -28,
      shadows: 16,
      whites: -6,
      blacks: -14,
      temperature: 12,
      tint: 2,
      vibrance: 12,
      saturation: -4,
      clarity: 6,
      texture: 4,
      hslOrangeSat: 10,
      hslYellowSat: 6,
      gradeShadowHue: 25,
      gradeShadowSat: 12,
      gradeHighHue: 42,
      gradeHighSat: 18,
      gradeBlending: 60,
      vignetteAmount: -14,
      vignetteFeather: 65,
    },
  },

  // ── Automotive ───────────────────────────────────────────────────────────
  {
    id: 'auto-moody',
    name: 'Moody Automotive',
    category: 'Automotive',
    description: 'Harter Lokalkontrast auf Lack und Technik, dunkler Hintergrund.',
    vibe: 'moody automotive, dunkel und kontraststark, Lack soll plastisch wirken, Hintergrund zurückgenommen',
    values: {
      exposure: -0.15,
      contrast: 22,
      highlights: -40,
      shadows: -5,
      whites: -8,
      blacks: -25,
      temperature: -6,
      vibrance: 14,
      saturation: -10,
      clarity: 18,
      texture: 12,
      dehaze: 8,
      sharpenAmount: 50,
      sharpenRadius: 0.9,
      sharpenMasking: 25,
      gradeShadowHue: 220,
      gradeShadowSat: 14,
      gradeHighHue: 35,
      gradeHighSat: 8,
      vignetteAmount: -25,
      vignetteMidpoint: 40,
      vignetteFeather: 55,
    },
  },
  {
    id: 'auto-clean',
    name: 'Clean Automotive',
    category: 'Automotive',
    description: 'Neutral, hell, werblich — zeigt Farbe und Form ohne Stilisierung.',
    vibe: 'clean, neutral, hell, werbliche Produktfotografie, Farben korrekt und kräftig, keine Stilisierung',
    values: {
      contrast: 10,
      highlights: -20,
      shadows: 10,
      whites: 8,
      blacks: -8,
      vibrance: 14,
      clarity: 10,
      texture: 6,
      sharpenAmount: 55,
      sharpenRadius: 0.8,
      sharpenMasking: 30,
    },
  },
  {
    id: 'auto-night-drive',
    name: 'Night Drive',
    category: 'Automotive',
    description: 'Nachtaufnahmen mit Kunstlicht: kräftige Lichtquellen, kühle Umgebung.',
    vibe: 'Nacht, Kunstlicht, kühle Umgebung mit warmen Lichtquellen, Details in den Schatten sollen sichtbar bleiben',
    values: {
      exposure: -0.15,
      contrast: 18,
      highlights: -25,
      shadows: 22,
      whites: -10,
      blacks: -22,
      temperature: -14,
      tint: 4,
      vibrance: 18,
      saturation: -6,
      clarity: 12,
      dehaze: 6,
      noiseLuminance: 22,
      noiseColor: 32,
      hslOrangeSat: 15,
      hslYellowSat: 10,
      hslBlueLum: -12,
      hslBlueSat: 10,
      gradeShadowHue: 225,
      gradeShadowSat: 20,
      gradeHighHue: 38,
      gradeHighSat: 12,
      vignetteAmount: -20,
    },
  },
  {
    id: 'auto-street',
    name: 'Street',
    category: 'Automotive',
    description: 'Rauer Reportagelook mit Struktur und dezentem Korn.',
    vibe: 'roh, dokumentarisch, strukturbetont, leicht entsättigt, sichtbares Korn',
    values: {
      contrast: 14,
      highlights: -22,
      shadows: 8,
      blacks: -16,
      saturation: -15,
      vibrance: 10,
      texture: 16,
      clarity: 12,
      sharpenAmount: 45,
      sharpenMasking: 20,
      grainAmount: 22,
      grainSize: 28,
      vignetteAmount: -12,
    },
  },

  // ── Natur ────────────────────────────────────────────────────────────────
  {
    id: 'nature-natural',
    name: 'Natural',
    category: 'Natur',
    description: 'Dezente Korrektur, wie ein Fotograf sie als Grundlage anlegt.',
    vibe: 'natürlich, unaufdringlich, korrekte Farben, nur eine saubere Grundbearbeitung ohne erkennbaren Stil',
    values: {
      contrast: 6,
      highlights: -16,
      shadows: 12,
      whites: 6,
      blacks: -6,
      vibrance: 8,
      clarity: 4,
      sharpenAmount: 40,
      sharpenRadius: 0.8,
      sharpenMasking: 25,
    },
  },
  {
    id: 'nature-vibrant',
    name: 'Vibrant Nature',
    category: 'Natur',
    description: 'Kräftiges Grün und Blau, ohne dass Farben unnatürlich kippen.',
    vibe: 'kräftige, lebendige Naturfarben, sattes Grün und tiefes Blau, trotzdem glaubwürdig',
    values: {
      contrast: 12,
      highlights: -22,
      shadows: 12,
      whites: 8,
      blacks: -10,
      vibrance: 26,
      saturation: 4,
      clarity: 12,
      texture: 8,
      hslGreenHue: -10,
      hslGreenSat: 14,
      hslGreenLum: 6,
      hslYellowSat: 8,
      hslBlueSat: 14,
      hslAquaSat: 8,
      sharpenAmount: 50,
      sharpenMasking: 30,
    },
  },
  {
    id: 'nature-golden',
    name: 'Golden Hour',
    category: 'Natur',
    description: 'Warmes Abendlicht mit weichen Lichtern und kühlem Gegenpol im Schatten.',
    vibe: 'goldenes Abendlicht, warm und weich, Sonnenuntergangsstimmung, Schatten leicht kühl als Gegenpol',
    values: {
      exposure: 0.05,
      contrast: 8,
      highlights: -26,
      shadows: 16,
      whites: -4,
      blacks: -10,
      temperature: 18,
      tint: 4,
      vibrance: 16,
      clarity: 6,
      hslOrangeSat: 12,
      hslYellowSat: 10,
      hslYellowLum: 4,
      gradeShadowHue: 220,
      gradeShadowSat: 10,
      gradeHighHue: 36,
      gradeHighSat: 20,
      gradeBlending: 60,
      vignetteAmount: -10,
    },
  },

  // ── Urban ────────────────────────────────────────────────────────────────
  {
    id: 'urban-night',
    name: 'Urban Night',
    category: 'Urban',
    description: 'Großstadt bei Nacht: Neon bleibt bunt, Rauschen wird gebändigt.',
    vibe: 'Großstadt bei Nacht, Neonlichter kräftig, tiefe Schatten, sauberes Rauschverhalten',
    values: {
      exposure: -0.1,
      contrast: 20,
      highlights: -28,
      shadows: 20,
      whites: -8,
      blacks: -28,
      temperature: -12,
      vibrance: 22,
      saturation: -6,
      clarity: 14,
      dehaze: 10,
      noiseLuminance: 28,
      noiseColor: 38,
      hslMagentaSat: 12,
      hslBlueSat: 12,
      hslOrangeSat: 10,
      gradeShadowHue: 230,
      gradeShadowSat: 18,
      gradeHighHue: 300,
      gradeHighSat: 8,
      vignetteAmount: -18,
    },
  },
  {
    id: 'urban-clean',
    name: 'Clean City',
    category: 'Urban',
    description: 'Architektur bei Tag: gerade, klar, mit präziser Kantenschärfe.',
    vibe: 'klare Architekturfotografie bei Tag, präzise und sauber, Farben leicht zurückgenommen',
    values: {
      contrast: 12,
      highlights: -25,
      shadows: 15,
      whites: 10,
      blacks: -10,
      vibrance: 10,
      saturation: -5,
      clarity: 14,
      texture: 8,
      dehaze: 6,
      sharpenAmount: 58,
      sharpenRadius: 0.8,
      sharpenDetail: 30,
      sharpenMasking: 35,
    },
  },
  {
    id: 'urban-dark',
    name: 'Dark City',
    category: 'Urban',
    description: 'Fast monochromer Betonlook mit sehr tiefem Schwarz.',
    vibe: 'düster, fast monochrom, Beton und Stahl, sehr tiefes Schwarz, harte Stimmung',
    values: {
      exposure: -0.25,
      contrast: 20,
      highlights: -35,
      shadows: -8,
      whites: -10,
      blacks: -30,
      temperature: -10,
      saturation: -18,
      vibrance: 12,
      clarity: 16,
      texture: 10,
      dehaze: 8,
      gradeShadowHue: 215,
      gradeShadowSat: 16,
      vignetteAmount: -28,
      vignetteMidpoint: 42,
    },
  },

  // ── Film ─────────────────────────────────────────────────────────────────
  {
    id: 'film-soft',
    name: 'Soft Film',
    category: 'Film',
    description: 'Angehobene Schwarzwerte, weiche Lichter, feines Korn.',
    vibe: 'weicher Filmlook, matte angehobene Schwarztöne, sanfte Lichter, feines Korn, zurückhaltende Farben',
    values: {
      contrast: -8,
      highlights: -18,
      shadows: 22,
      whites: -12,
      blacks: 12,
      temperature: 4,
      vibrance: 6,
      saturation: -6,
      texture: -6,
      clarity: -4,
      grainAmount: 28,
      grainSize: 30,
      grainRoughness: 55,
      gradeShadowHue: 185,
      gradeShadowSat: 10,
      gradeHighHue: 45,
      gradeHighSat: 12,
      gradeBlending: 60,
    },
    curve: [
      { x: 0, y: 0.055 },
      { x: 0.25, y: 0.27 },
      { x: 0.75, y: 0.77 },
      { x: 1, y: 0.965 },
    ],
  },
  {
    id: 'film-classic',
    name: 'Classic Film',
    category: 'Film',
    description: 'Kräftiger Negativfilm-Charakter mit verschobenem Grün.',
    vibe: 'klassischer Negativfilm, kräftig aber nicht knallig, leicht verschobene Grüntöne, sichtbares Korn',
    values: {
      contrast: 12,
      highlights: -22,
      shadows: 10,
      whites: -6,
      blacks: 8,
      temperature: 6,
      tint: -2,
      vibrance: 12,
      saturation: -10,
      texture: 6,
      grainAmount: 34,
      grainSize: 26,
      hslOrangeSat: 10,
      hslOrangeHue: -4,
      hslGreenHue: 14,
      hslGreenSat: -12,
      hslBlueSat: 6,
      gradeShadowHue: 200,
      gradeShadowSat: 14,
      gradeHighHue: 40,
      gradeHighSat: 10,
    },
  },
  {
    id: 'film-vintage',
    name: 'Vintage Film',
    category: 'Film',
    description: 'Ausgeblichene Farben, warmer Stich, deutliches Korn.',
    vibe: 'vintage, ausgeblichen, warmer Gelbstich, niedriger Kontrast, deutliches Korn, wie ein altes Foto',
    values: {
      contrast: -6,
      highlights: -14,
      shadows: 18,
      whites: -16,
      blacks: 20,
      temperature: 12,
      tint: 6,
      vibrance: 8,
      saturation: -22,
      texture: -4,
      grainAmount: 45,
      grainSize: 40,
      grainRoughness: 60,
      hslBlueSat: -20,
      hslAquaSat: -12,
      gradeShadowHue: 42,
      gradeShadowSat: 18,
      gradeHighHue: 52,
      gradeHighSat: 20,
      gradeBlending: 45,
      vignetteAmount: -16,
      vignetteFeather: 70,
    },
    curve: [
      { x: 0, y: 0.09 },
      { x: 0.3, y: 0.33 },
      { x: 0.7, y: 0.7 },
      { x: 1, y: 0.93 },
    ],
  },

  // ── Schwarzweiß ──────────────────────────────────────────────────────────
  {
    id: 'bw-classic',
    name: 'Klassisch S/W',
    category: 'Schwarzweiß',
    description: 'Ausgewogenes Schwarzweiß mit heller Hautwiedergabe.',
    vibe: 'klassisches Schwarzweiß, ausgewogene Tonwerte, Hauttöne hell, Himmel etwas dunkler',
    values: {
      saturation: -100,
      contrast: 14,
      highlights: -18,
      shadows: 14,
      whites: 8,
      blacks: -12,
      clarity: 10,
      texture: 8,
      hslRedLum: 12,
      hslOrangeLum: 18,
      hslYellowLum: 10,
      hslBlueLum: -22,
      hslAquaLum: -12,
      sharpenAmount: 45,
      sharpenMasking: 25,
    },
  },
  {
    id: 'bw-contrast',
    name: 'Kontrastreich S/W',
    category: 'Schwarzweiß',
    description: 'Harte Schwarzweiß-Umsetzung mit Korn und tiefem Schwarz.',
    vibe: 'hartes, grafisches Schwarzweiß, tiefes Schwarz, helle Lichter, deutliches Korn',
    values: {
      saturation: -100,
      contrast: 28,
      highlights: -25,
      shadows: 8,
      whites: 12,
      blacks: -28,
      clarity: 18,
      texture: 14,
      dehaze: 6,
      hslOrangeLum: 14,
      hslBlueLum: -30,
      grainAmount: 30,
      grainSize: 30,
      vignetteAmount: -20,
      sharpenAmount: 55,
      sharpenMasking: 30,
    },
  },
];

export const PRESET_BY_ID: ReadonlyMap<string, Preset> = new Map(PRESETS.map((p) => [p.id, p]));

export function presetsByCategory(): { category: string; presets: Preset[] }[] {
  return PRESET_CATEGORIES.map((category) => ({
    category,
    presets: PRESETS.filter((p) => p.category === category),
  })).filter((g) => g.presets.length > 0);
}
